table Dim_Week
	lineageTag: 8628463d-3e2c-47d6-a4f3-8f4cf6e2d32e

	column week_number
		dataType: int64
		summarizeBy: none
		sourceColumn: week_number

	column observation_week
		dataType: string
		summarizeBy: none
		sourceColumn: observation_week

	column synthetic_week_start
		dataType: dateTime
		summarizeBy: none
		sourceColumn: synthetic_week_start

	column month_label
		dataType: string
		summarizeBy: none
		sourceColumn: month_label

	partition Dim_Week = m
		mode: import
		source =
			let
				Source = Parquet.Document(Binary.Buffer(File.Contents("D:\data\Codex\_retail_da_stage_20260922\run\05_powerbi_exports\Dim_Week.parquet"))),
				#"Added Month Label" = Table.AddColumn(Source, "month_label", each Date.ToText(Date.From([synthetic_week_start]), "yyyy-MM"), type text)
			in
				#"Added Month Label"

	annotation PBI_ResultType = Table
