-- Governed decision register consumed by BI exports. Numeric findings remain in
-- evidence tables; this table stores the question, action, monitor and limits.
CREATE OR REPLACE TABLE analysis_executive_decisions AS
SELECT * FROM (VALUES
    ('D01', 'Panel Spend Movement', 'Explain the reconciled movement using active households, trips and spend per basket', 'Test the largest reconciled driver with a defined guardrail', 'Panel Net Spend; Active Panel Households; Trips per Active Household; Spend per Basket', 'analysis_root_cause_lmdi', 'READY_FOR_REVIEW', 'Observed panel spend is not retailer revenue; decomposition is associative'),
    ('D02', 'High-Value Declining Households', 'Prioritize high-value households with a declining late-window trajectory', 'Test targeted re-engagement and monitor return frequency', 'High-Value Declining count; spend recovery; trips per household', 'mart_customer_segment', 'READY_FOR_REVIEW', 'First observed purchase is not acquisition; panel behavior may evolve'),
    ('D03', 'Category Erosion', 'Rank category spend movement with household, basket and basket-value drivers', 'Investigate category-specific assortment, price and promotion hypotheses', 'Category spend; buying households; category baskets; spend per category basket', 'analysis_category_decomposition', 'READY_FOR_REVIEW', 'Category results are observational and use observation weeks'),
    ('D04', 'Promotion-State Difference', 'Compare observed promotion states with sample sizes and association tests', 'Run a controlled merchandising test only if a valid comparison universe exists', 'Product-store-weeks; sales per product-store-week; effect size', 'analysis_promotion_universe_audit', 'READY_FOR_REVIEW', 'No causal uplift claim; none state may be absent'),
    ('D05', 'Campaign Response', 'Separate exposure-level from unique-household response and show Wilson intervals', 'Review targeting and redemption mechanics before changing campaign allocation', 'Exposure redemption rate; unique-household redemption rate; CI; observable post rows', 'analysis_campaign_denominators', 'READY_FOR_REVIEW', 'Targeting bias and post-window censoring apply; no ROI claim')
) AS t(decision_id, business_question, verified_finding, proposed_test, monitoring_kpi, evidence_source, status, limitation);
