CREATE OR REPLACE VIEW stg_product AS
SELECT DISTINCT
    CAST(PRODUCT_ID AS BIGINT) AS product_id,
    CAST(MANUFACTURER AS VARCHAR) AS manufacturer_id,
    CAST(DEPARTMENT AS VARCHAR) AS department,
    CASE
        WHEN LOWER(TRIM(CAST(BRAND AS VARCHAR))) = 'private' THEN 'PRIVATE'
        WHEN LOWER(TRIM(CAST(BRAND AS VARCHAR))) = 'national' THEN 'NATIONAL'
        ELSE COALESCE(NULLIF(TRIM(CAST(BRAND AS VARCHAR)), ''), 'Unknown')
    END AS brand_type,
    CAST(COMMODITY_DESC AS VARCHAR) AS commodity,
    CAST(SUB_COMMODITY_DESC AS VARCHAR) AS sub_commodity,
    CAST(CURR_SIZE_OF_PRODUCT AS VARCHAR) AS product_size
FROM raw_product;
