CREATE OR REPLACE VIEW stg_product AS
SELECT DISTINCT
    CAST(PRODUCT_ID AS BIGINT) AS product_id,
    CAST(MANUFACTURER AS VARCHAR) AS manufacturer_id,
    CAST(DEPARTMENT AS VARCHAR) AS department,
    CAST(BRAND AS VARCHAR) AS brand_type_raw,
    UPPER(TRIM(CAST(BRAND AS VARCHAR))) AS brand_type,
    CAST(COMMODITY_DESC AS VARCHAR) AS commodity,
    CAST(SUB_COMMODITY_DESC AS VARCHAR) AS sub_commodity,
    CAST(CURR_SIZE_OF_PRODUCT AS VARCHAR) AS product_size
FROM raw_product;
